FROM python:3.8
WORKDIR /code
COPY requirements.txt /
RUN pip install -r /requirements.txt
COPY ./ ./
EXPOSE 8080
CMD ["python", "./front_end/index.py"]

FROM amazon/aws-eb-python:3.4.2-onbuild-3.5.1
